[build]
  command = "npm run build && sed -i 's|__SUPABASE_URL__|'\"$VITE_SUPABASE_URL\"'|g' dist/chat.html && sed -i 's|__SUPABASE_ANON_KEY__|'\"$VITE_SUPABASE_ANON_KEY\"'|g' dist/chat.html"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
